services:

  backend:
    build:
      context: ./main
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  

volumes:
  postgres_data: