# Generated by Django 5.0.7 on 2024-07-26 16:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key_word', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключивые слова',
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key_word', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('question', models.TextField()),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('key_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.keyword')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserMaterials',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.user', unique=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('user_phone', models.CharField(max_length=15)),
                ('material_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.material', unique=True)),
            ],
            options={
                'verbose_name': 'Материал пользователя',
                'verbose_name_plural': 'Материалы пользователя',
                'db_table': 'user_materials',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='users',
            field=models.ManyToManyField(through='main.UserMaterials', to='main.user'),
        ),
        migrations.AddConstraint(
            model_name='usermaterials',
            constraint=models.UniqueConstraint(fields=('user_id', 'material_id'), name='unique_migration_host_combination'),
        ),
    ]
